import Head from 'next/head'
import Image from 'next/image'

import { Plan, PlanDetails } from "../src/components";
import styles from '../styles/Home.module.css'

const plans = [
  {
    title: 'plan 1',
    subTitle: 'subTitle plan 1',
    backgroundImage: '/img.png',
    overlayBgColor: '#6AFBC6',
  },
  {
    title: 'plan 2',
    subTitle: 'subTitle plan 2',
    backgroundImage: '/img.png',
    overlayBgColor: '#FFDE33',
  },
  {
    title: 'plan 3',
    subTitle: 'subTitle plan 3',
    backgroundImage: '/img.png',
    overlayBgColor: '#16D2EC',
  },
]
const plansDetails = [
  {
    title: 'plan 1',
    price: '1$',
    benefits: ['Lorem ipsum dolor', 'Lorem ipsum dolor', 'Lorem ipsum dolor', 'Lorem ipsum dolor', 'Lorem ipsum dolor',],
    handler: () => undefined,
  },
  {
    title: 'plan 2',
    price: '22$',
    benefits: ['Lorem ipsum dolor', 'Lorem ipsum dolor', 'Lorem ipsum dolor', 'Lorem ipsum dolor', 'Lorem ipsum dolor',],
    handler: () => undefined,
  },
  {
    title: 'plan 3',
    price: '333$',
    benefits: ['Lorem ipsum dolor', 'Lorem ipsum dolor', 'Lorem ipsum dolor', 'Lorem ipsum dolor', 'Lorem ipsum dolor',],
    handler: () => undefined,
  },
]


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.menuWrapper}>
          <button className={styles.menuBtn}>
            <Image
              className={styles.menuBtnImage}
              src="/hamburger.svg"
              alt="menu"
              width={72}
              height={16}
            />
          </button>
          <span className={styles.menuTitle}>Menu</span>
        </div>
        <div>
          <Image
            className={styles.logoImage}
            src="/DocHQ_Logo.png"
            alt="DocHQ Logo"
            width={72}
            height={16}
          />
        </div>
        <div className={styles.hidden}/>
      </header>

      <section className={styles.underHeaderList}>
        <span className={styles.underHeaderListItem}>covid test</span>
        <span className={styles.underHeaderListItem}>health app</span>
        <span className={styles.underHeaderListItem}>supplements</span>
      </section>

      <main>
        <section className={styles.plans}>
          <div className={styles.container}>
            <p className={styles.plansSubtitle}>
              Complete our simple fitness assesment and recieve your personalised workout plans to
              get you one step closer to achieving your fitness goals.
            </p>
            <h4 className={styles.plansTitle}>Take our quick & easy fitness quiz in just 2 mins!</h4>
            <ol className={styles.cardWrapper}>
              {plans.map(({ title, subTitle, backgroundImage}) => {
                return (
                  <Plan key={title} title={title} backgroundImage={backgroundImage} subTitle={subTitle}/>)
              })}
            </ol>
          </div>
        </section>
        <section className={styles.detailsContainer}>
          <div className={styles.container}>
            <ol className={styles.planDetailsList}>
              {plansDetails.map(({ title, price, benefits, handler}, i) => {
                return (
                  <PlanDetails key={title} title={title} benefits={benefits} index={i}/>
                )
              })}
            </ol>
          </div>
        </section>
      </main>
    </>
  )
}



